[package]
name = "shaken"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
log = "0.4.3"
simplelog = "0.5.3"

rand = "0.5.4"
chrono = "0.4.4"

crossbeam-channel = "0.2.3"
parking_lot = "0.6.3"
scoped_threadpool = "0.1.9"

serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
toml = "0.4.6"

curl = "0.4.12"

rusqlite = { version = "0.15.0", features = ["bundled", "chrono"]}
