[package]
name = "shaken"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
simplelog = "0.5.3"
rand = "0.6.1"
chrono = "0.4.6"

serde = { version = "1.0.82", features = ["derive"] }
serde_json = "1.0.33"
toml = "0.4.10"

rusqlite = { version = "0.16.0", features = ["bundled", "chrono"] }
hashbrown = "0.1.7"

crossbeam-channel = "0.3.4" # is this used
scoped_threadpool = "0.1.9" # is this used
curl = "0.4.19" # get rid of this
