[package]
name = "shaken"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]

[dependencies]
log = "0.4.3"
env_logger = "0.5.10"
rand = "0.5.4"
chrono = "0.4.4"

crossbeam-channel = "0.2.3"
parking_lot = "0.6.3"

serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
toml = "0.4.6"

curl = "0.4.12"

url = "1.7.1"
tungstenite = "0.6.0"

rusqlite = { version = "0.13.0", features = ["bundled", "chrono"]}
# r2d2_sqlite = "0.5.0"
# r2d2 = "0.8.2"
